name: Build Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Install libs
      run: sudo apt-get install -y libgtk2.0-dev libva-dev

    - name: Install Conan
      run: pip install conan

    - name: Configure
      run: cmake -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -B build -G "Unix Makefiles"

    - name: Build
      run: cmake --build build --config RelWithDebInfo --target all
